# circleci hugo
version: 2
jobs:
  build:
    branches:
      only:
        - master
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:0.55.5
      #- image: flcker/hugo:latest
    working_directory: ~/hugo/
    environment:
      HUGO_SRC_DIR: ./hugo_sites
      HUGO_BUILD_DIR: ./hugo_public
      HUGO_VERSION: 0.55.5
      HUGO_ARCH: 64bit
      HUGO_SYSTEM: Linux
      HUGO_TMP: /tmp/hugo
    steps:

      # install git
      - run: apk update && apk add git openssh-client

      # create tmp dir
      #- run: mkdir -p $HUGO_TMP
      
      # download hugo bin
      #- run: curl -fSL https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_$HUGO_SYSTEM-$HUGO_ARCH.tar.gz -o hugo.tar.gz
      #- run: tar -zxf hugo.tar.gz -C $HUGO_TMP
      #- run: rm hugo.tar.gz
      #- run: mv $HUGO_TMP/hugo /usr/bin && rm -rf $HUGO_TMP

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # Link the public dir to the gh-pages branch

      - run: rm -fr $HUGO_BUILD_DIR && git worktree add -B gh-pages $HUGO_BUILD_DIR origin/gh-pages
      - run: pwd && ls -al
      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR -s $HUGO_SRC_DIR

      # Set some variables to add to the commit message
      - run: git config --global user.email "molanyousi@gmail.com" && git config --global user.name "flcker"

      # Push the generated files back to github
      - run: cd $HUGO_BUILD_DIR && git add --all && git commit -m "Automated publish to gh-pages [ci skip]" && git push